### ISSUE TITLE
As user I want "All news button" not to be textfield 

### ISSUE THREAD

**Issue by olegbbtr** [goto-ru/gotosite#18]
![selection_155](https://cloud.githubusercontent.com/assets/2663743/17151378/f6ef6654-53a5-11e6-8277-3d1aff731547.png)
![selection_156](https://cloud.githubusercontent.com/assets/2663743/17151331/d6559224-53a5-11e6-9eb2-3b1d67a6c493.png)

**Comment by tvorogme** [comment]
@Omrigan,  look [here](https://github.com/goto-ru/gotosite/commit/44f2a9b372e5eaa7be272bbbba2796ef9b7bfa40#diff-fb5aa1cd1261d08d02db6f7dc314d9abR121).

**Comment by tvorogme** [comment]
[Last commit](https://github.com/goto-ru/gotosite/commit/14d3f04d1c32f2961668d6d7601dbc1426f4dac6) fix it.
