### ISSUE TITLE
As maintainer I want README badges to be fixed 

### ISSUE THREAD

**Issue by olegbbtr** [goto-ru/gotosite#21]

**Comment by wldhx** [comment]
@Omrigan I don't have much clue what you're talking about. Elaborate.

**Comment by olegbbtr** [comment]
@wldhx Look at readme at develop branch. Badges on top aren't clickable, and there are unnecessary badges at the bottom. That occurred after migrating to markdown from rst. I'd prefer to leave readme in markdown formad
